DROP DATABASE IF EXISTS new_database;

CREATE DATABASE new_database
    DEFAULT CHARACTER SET = 'utf8mb4';

USE new_database;

DROP TABLE IF EXISTS geko_lahan_staging;

CREATE TABLE geko_lahan_staging (
    id INT,
    lahan_no VARCHAR(100),
    document_no VARCHAR(100),
    internal_code VARCHAR(100),
    land_area VARCHAR(50),
    planting_area VARCHAR(50),
    longitude VARCHAR(50),
    latitude VARCHAR(50),
    coordinate TEXT,
    polygon TEXT,
    nearby_village VARCHAR(100),
    nearby_village_distance VARCHAR(50),
    village VARCHAR(50),
    kecamatan VARCHAR(50),
    city VARCHAR(50),
    province VARCHAR(50),
    description TEXT,
    elevation VARCHAR(50),
    soil_type VARCHAR(100),
    soil_photo VARCHAR(255),
    current_crops TEXT,
    active INT,
    farmer_no VARCHAR(100),
    farmer_temp VARCHAR(100),
    mu_no VARCHAR(50),
    target_area VARCHAR(50),
    user_id VARCHAR(50),
    created_time VARCHAR(50),
    created_at VARCHAR(50),
    updated_at VARCHAR(50),
    sppt VARCHAR(255),
    tutupan_lahan VARCHAR(50),
    tutupan_pohon_percentage VARCHAR(50),
    tutupan_pohon_photo VARCHAR(255),
    tutupan_tanaman_bawah_percentage VARCHAR(50),
    tutupan_tanaman_bawah_photo VARCHAR(255),
    tutupan_lain_bangunan_percentage VARCHAR(50),
    tutupan_lain_bangunan_photo VARCHAR(255),
    photo1 VARCHAR(255),
    photo2 VARCHAR(255),
    photo3 VARCHAR(255),
    photo4 VARCHAR(255),
    group_no VARCHAR(50),
    kelerengan_lahan VARCHAR(50),
    fertilizer VARCHAR(50),
    pesticide VARCHAR(50),
    access_to_water_sources VARCHAR(50),
    water_availability VARCHAR(100),
    water_availability_level VARCHAR(50),
    access_to_lahan VARCHAR(50),
    potency VARCHAR(50),
    barcode VARCHAR(100),
    lahan_type VARCHAR(100),
    jarak_lahan VARCHAR(50),
    exposure VARCHAR(50),
    opsi_pola_tanam VARCHAR(100),
    pohon_kayu VARCHAR(50),
    pohon_mpts VARCHAR(50),
    tanaman_bawah VARCHAR(50),
    type_sppt VARCHAR(50),
    is_dell INT,
    complete_data INT,
    fc_complete_data INT,
    fc_complete_data_at VARCHAR(50),
    fc_complete_data_by VARCHAR(100),
    approve INT,
    approved_by VARCHAR(100),
    approved_at VARCHAR(50),
    eligible_status VARCHAR(50),
    update_eligible_at VARCHAR(50),
    update_eligible_by VARCHAR(100),
    force_majeure_description TEXT,
    floods INT,
    wildfire INT,
    landslide INT,
    drought INT,
    animal_protected_habitat INT,
    animal_protected_habitat_distance VARCHAR(50),
    latest_condition VARCHAR(50),
    polygon_from_ff TEXT,
    polygon_from_gis TEXT,
    gis_polygon_area VARCHAR(50),
    gis_planting_area VARCHAR(50),
    gis_planting_enhancement_area VARCHAR(50),
    gis_planting_enhancement_polygon TEXT,
    gis_arr_area VARCHAR(50),
    gis_arr_polygon TEXT,
    updated_gis VARCHAR(50),
    gis_updated_at VARCHAR(50),
    gis_officer VARCHAR(100),
    gis_not_eligible_status VARCHAR(50),
    gps_accuration VARCHAR(50),
    status VARCHAR(50),
    status_perubahan_tutupan VARCHAR(50),
    plant_status VARCHAR(50),
    seed_is_modified INT,
    seed_verify_status INT,
    seed_verify_at VARCHAR(50),
    seed_verify_by VARCHAR(100),
    mou_complete_status INT,
    land_mou_agreement TEXT,
    land_mou_attachment VARCHAR(255),
    polygon_tutupan_area VARCHAR(50),
    polygon_tutupan_photo VARCHAR(255),
    polygon_tutupan_status INT,
    polygon_tutupan_by VARCHAR(100),
    polygon_tutupan_at VARCHAR(50),
    gis_eligibility_status VARCHAR(50),
    gis_eligibility_type VARCHAR(50),
    gis_eligibility_srnppi VARCHAR(50),
    gis_update_eligibility_at VARCHAR(50),
    legal_eligibility_status VARCHAR(50),
    legal_eligibility_by VARCHAR(100),
    legal_eligibility_at VARCHAR(50),
    penebangan_kayu VARCHAR(50),
    kawasan_hutan VARCHAR(50),
    satwa_sekitar VARCHAR(50),
    pohon_endemic VARCHAR(50)
);

SHOW GLOBAL VARIABLES LIKE 'local_infile';
SET GLOBAL local_infile = 1;

-- Import CSV file GEKO Lahan
LOAD DATA LOCAL INFILE 'E:/Test Kerja/trees4tress/migrasi-data/database/data/LahanGEKO_2023 3(in).csv'
INTO TABLE geko_lahan_staging
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    @id_var, lahan_no, document_no, internal_code,
    land_area, planting_area,
    longitude, latitude, coordinate, polygon,
    @nearby_village, @nearby_village_distance, village, kecamatan, city, province,
    description, elevation, soil_type, soil_photo, current_crops,
    @active_var,
    farmer_no, farmer_temp, mu_no, target_area, user_id, created_time, created_at, updated_at,
    sppt, tutupan_lahan, @tutupan_pohon_percentage, @tutupan_pohon_photo,
    @tutupan_tanaman_bawah_percentage, @tutupan_tanaman_bawah_photo,
    @tutupan_lain_bangunan_percentage, @tutupan_lain_bangunan_photo,
    photo1, photo2, photo3, photo4,
    group_no, kelerengan_lahan, fertilizer, pesticide,
    access_to_water_sources, water_availability, @water_availability_level, access_to_lahan,
    potency, barcode, lahan_type, jarak_lahan, exposure, opsi_pola_tanam,
    pohon_kayu, pohon_mpts, tanaman_bawah, type_sppt,
    @is_dell_var, @complete_data_var, @fc_complete_data_var, @fc_complete_data_at, @fc_complete_data_by,
    @approve_var, @approved_by, @approved_at,
    eligible_status, @update_eligible_at, @update_eligible_by,
    @force_majeure_description, @floods_var, @wildfire_var, @landslide_var, @drought_var,
    @animal_protected_habitat_var, @animal_protected_habitat_distance,
    latest_condition,
    @polygon_from_ff, @polygon_from_gis, gis_polygon_area, gis_planting_area,
    gis_planting_enhancement_area, @gis_planting_enhancement_polygon, gis_arr_area, @gis_arr_polygon,
    updated_gis, @gis_updated_at, @gis_officer, @gis_not_eligible_status, gps_accuration,
    status, status_perubahan_tutupan, plant_status,
    @seed_is_modified_var, @seed_verify_status_var, @seed_verify_at, @seed_verify_by,
    @mou_complete_status_var, @land_mou_agreement, @land_mou_attachment,
    polygon_tutupan_area, @polygon_tutupan_photo, @polygon_tutupan_status_var, @polygon_tutupan_by, @polygon_tutupan_at,
    gis_eligibility_status, gis_eligibility_type, gis_eligibility_srnppi, @gis_update_eligibility_at,
    @legal_eligibility_status, @legal_eligibility_by, @legal_eligibility_at,
    penebangan_kayu, kawasan_hutan, satwa_sekitar, pohon_endemic
)
SET
    id = NULLIF(@id_var, ''),
    nearby_village = NULLIF(@nearby_village, '\\N'),
    nearby_village_distance = NULLIF(@nearby_village_distance, '\\N'),
    active = NULLIF(@active_var, ''),
    tutupan_pohon_percentage = NULLIF(@tutupan_pohon_percentage, '\\N'),
    tutupan_pohon_photo = NULLIF(@tutupan_pohon_photo, '\\N'),
    tutupan_tanaman_bawah_percentage = NULLIF(@tutupan_tanaman_bawah_percentage, '\\N'),
    tutupan_tanaman_bawah_photo = NULLIF(@tutupan_tanaman_bawah_photo, '\\N'),
    tutupan_lain_bangunan_percentage = NULLIF(@tutupan_lain_bangunan_percentage, '\\N'),
    tutupan_lain_bangunan_photo = NULLIF(@tutupan_lain_bangunan_photo, '\\N'),
    water_availability_level = NULLIF(@water_availability_level, '\\N'),
    is_dell = NULLIF(@is_dell_var, ''),
    complete_data = NULLIF(@complete_data_var, ''),
    fc_complete_data = NULLIF(@fc_complete_data_var, ''),
    fc_complete_data_at = NULLIF(@fc_complete_data_at, '\\N'),
    fc_complete_data_by = NULLIF(@fc_complete_data_by, '\\N'),
    approve = NULLIF(@approve_var, ''),
    approved_by = NULLIF(@approved_by, '\\N'),
    approved_at = NULLIF(@approved_at, '\\N'),
    update_eligible_at = NULLIF(@update_eligible_at, '\\N'),
    update_eligible_by = NULLIF(@update_eligible_by, '\\N'),
    force_majeure_description = NULLIF(@force_majeure_description, '\\N'),
    floods = NULLIF(@floods_var, ''),
    wildfire = NULLIF(@wildfire_var, ''),
    landslide = NULLIF(@landslide_var, ''),
    drought = NULLIF(@drought_var, ''),
    animal_protected_habitat = NULLIF(@animal_protected_habitat_var, ''),
    animal_protected_habitat_distance = NULLIF(@animal_protected_habitat_distance, '\\N'),
    polygon_from_ff = NULLIF(@polygon_from_ff, '\\N'),
    polygon_from_gis = NULLIF(@polygon_from_gis, '\\N'),
    gis_planting_enhancement_polygon = NULLIF(@gis_planting_enhancement_polygon, '\\N'),
    gis_arr_polygon = NULLIF(@gis_arr_polygon, '\\N'),
    gis_updated_at = NULLIF(@gis_updated_at, '\\N'),
    gis_officer = NULLIF(@gis_officer, '\\N'),
    gis_not_eligible_status = NULLIF(@gis_not_eligible_status, '\\N'),
    seed_is_modified = NULLIF(@seed_is_modified_var, ''),
    seed_verify_status = NULLIF(@seed_verify_status_var, ''),
    seed_verify_at = NULLIF(@seed_verify_at, '\\N'),
    seed_verify_by = NULLIF(@seed_verify_by, '\\N'),
    mou_complete_status = NULLIF(@mou_complete_status_var, ''),
    land_mou_agreement = NULLIF(@land_mou_agreement, '\\N'),
    land_mou_attachment = NULLIF(@land_mou_attachment, '\\N'),
    polygon_tutupan_photo = NULLIF(@polygon_tutupan_photo, '\\N'),
    polygon_tutupan_status = NULLIF(@polygon_tutupan_status_var, ''),
    polygon_tutupan_by = NULLIF(@polygon_tutupan_by, '\\N'),
    polygon_tutupan_at = NULLIF(@polygon_tutupan_at, '\\N'),
    gis_update_eligibility_at = NULLIF(@gis_update_eligibility_at, '\\N'),
    legal_eligibility_status = NULLIF(@legal_eligibility_status, '\\N'),
    legal_eligibility_by = NULLIF(@legal_eligibility_by, '\\N'),
    legal_eligibility_at = NULLIF(@legal_eligibility_at, '\\N');

-- Verifikasi hasil import
SELECT COUNT(*) AS total_rows FROM geko_lahan_staging;
SELECT * FROM geko_lahan_staging LIMIT 5;
